import os
from typing import List, Dict, Any
import httpx
from core.logger import logger

class BaseLLMGenerator:
    """Abstract interface for LLM response generation."""
    def generate(self, prompt: str, system_prompt: str = "", temperature: float = 0.2) -> str:
        raise NotImplementedError

class MockLLMGenerator(BaseLLMGenerator):
    """Built-in offline generator that builds grounded responses without needing external API keys."""

    def generate(self, prompt: str, system_prompt: str = "", temperature: float = 0.2) -> str:
        logger.info("Using MockLLMGenerator (Offline Mode)")
        
        if "Context Passages:" in prompt and "Question:" in prompt:
            try:
                context_part = prompt.split("Context Passages:")[1].split("Question:")[0]
                question_part = prompt.split("Question:")[1].split("Answer:")[0]
                
                answer = f"Based on the provided documents, here is the answer regarding '{question_part.strip()}':\n\n"
                answer += "Key relevant findings extracted from your technical research materials:\n"
                
                lines = [l.strip() for l in context_part.splitlines() if l.strip() and not l.startswith("[Passage") and not l.startswith("-----------------")]
                for line in lines[:3]:
                    if len(line) > 15:
                        answer += f"• {line}\n"
                        
                answer += "\n(Note: This response was generated by InsightRAG's built-in offline engine using retrieved context vector chunks.)"
                return answer
            except Exception:
                pass
                
        return "I am InsightRAG. Upload PDF documents and submit your query to retrieve grounded answers."

class OpenAIProvider(BaseLLMGenerator):
    """OpenAI API Integration."""
    def __init__(self, api_key: str):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY", "")

    def generate(self, prompt: str, system_prompt: str = "", temperature: float = 0.2) -> str:
        if not self.api_key:
            return "Error: OpenAI API key is missing. Please add it in Settings or switch to the Mock provider."
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": "gpt-3.5-turbo",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            "temperature": temperature
        }
        try:
            with httpx.Client(timeout=30.0) as client:
                res = client.post("https://api.openai.com/v1/chat/completions", json=payload, headers=headers)
                res.raise_for_status()
                data = res.json()
                return data["choices"][0]["message"]["content"]
        except Exception as e:
            logger.error(f"OpenAI generation error: {str(e)}")
            return f"Error connecting to OpenAI: {str(e)}"

class GroqProvider(BaseLLMGenerator):
    """Groq API Integration for fast Llama3 responses."""
    def __init__(self, api_key: str):
        self.api_key = api_key or os.getenv("GROQ_API_KEY", "")

    def generate(self, prompt: str, system_prompt: str = "", temperature: float = 0.2) -> str:
        if not self.api_key:
            return "Error: Groq API key is missing. Please set it in Settings."
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": "llama3-8b-8192",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            "temperature": temperature
        }
        try:
            with httpx.Client(timeout=30.0) as client:
                res = client.post("https://api.groq.com/openai/v1/chat/completions", json=payload, headers=headers)
                res.raise_for_status()
                data = res.json()
                return data["choices"][0]["message"]["content"]
        except Exception as e:
            logger.error(f"Groq generation error: {str(e)}")
            return f"Error connecting to Groq API: {str(e)}"

class GeminiProvider(BaseLLMGenerator):
    """Google Gemini API Integration."""
    def __init__(self, api_key: str):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY", "")

    def generate(self, prompt: str, system_prompt: str = "", temperature: float = 0.2) -> str:
        if not self.api_key:
            return "Error: Gemini API key is missing. Please set it in Settings."
        
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={self.api_key}"
        payload = {
            "contents": [
                {"parts": [{"text": f"{system_prompt}\n\n{prompt}"}]}
            ],
            "generationConfig": {
                "temperature": temperature
            }
        }
        try:
            with httpx.Client(timeout=30.0) as client:
                res = client.post(url, json=payload)
                res.raise_for_status()
                data = res.json()
                return data["candidates"][0]["content"]["parts"][0]["text"]
        except Exception as e:
            logger.error(f"Gemini API error: {str(e)}")
            return f"Error connecting to Google Gemini API: {str(e)}"

class OllamaProvider(BaseLLMGenerator):
    """Local Ollama instance integration."""
    def __init__(self, base_url: str = "http://localhost:11434"):
        self.base_url = base_url

    def generate(self, prompt: str, system_prompt: str = "", temperature: float = 0.2) -> str:
        url = f"{self.base_url}/api/generate"
        payload = {
            "model": "llama3",
            "system": system_prompt,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": temperature}
        }
        try:
            with httpx.Client(timeout=60.0) as client:
                res = client.post(url, json=payload)
                res.raise_for_status()
                return res.json().get("response", "")
        except Exception as e:
            logger.error(f"Ollama error: {str(e)}")
            return f"Could not connect to local Ollama server at {self.base_url}: {str(e)}"

class LLMGenerator:
    """Factory to get configured LLM provider instance."""

    @staticmethod
    def get_generator(provider: str = "mock", api_key: str = "") -> BaseLLMGenerator:
        provider = provider.lower()
        if provider == "openai":
            return OpenAIProvider(api_key=api_key)
        elif provider == "groq":
            return GroqProvider(api_key=api_key)
        elif provider == "gemini":
            return GeminiProvider(api_key=api_key)
        elif provider == "ollama":
            return OllamaProvider()
        else:
            return MockLLMGenerator()
